// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: JC3248W535CIY

#include "../ui.h"

void ui_mainScreen_screen_init(void)
{
ui_mainScreen = lv_obj_create(NULL);
lv_obj_remove_flag( ui_mainScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_mainScreen,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_mainScreen, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_set_style_bg_color(ui_mainScreen, lv_color_hex(0x0D0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_mainScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_src( ui_mainScreen, &ui_img_homebridge_color_round_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_pad_left(ui_mainScreen, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_mainScreen, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_mainScreen, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_mainScreen, 10, LV_PART_MAIN| LV_STATE_DEFAULT);


}
