// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: JC3248W535CIY

#include "../ui.h"

void ui_unSeen_screen_init(void)
{
ui_unSeen = lv_obj_create(NULL);
lv_obj_add_state( ui_unSeen, LV_STATE_CHECKED );     /// States
lv_obj_remove_flag( ui_unSeen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_unSeen,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_unSeen, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
lv_obj_set_style_pad_left(ui_unSeen, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_unSeen, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_unSeen, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_unSeen, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_unSeen, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_unSeen, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_omgLabelContainer = ui_omgLabelContainer_create(ui_unSeen);
lv_obj_set_x( ui_omgLabelContainer, 0 );
lv_obj_set_y( ui_omgLabelContainer, 0 );





}
