// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: JC3248W535CIY

#ifndef _UI_COMP_HKBUTTONCONTAINER_H
#define _UI_COMP_HKBUTTONCONTAINER_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT hkButtonContainer
#define UI_COMP_HKBUTTONCONTAINER_HKBUTTONCONTAINER 0
#define UI_COMP_HKBUTTONCONTAINER_CONTAINER3 1
#define UI_COMP_HKBUTTONCONTAINER_HKICON 2
#define UI_COMP_HKBUTTONCONTAINER_CONTAINER4 3
#define UI_COMP_HKBUTTONCONTAINER_HKLABELCONTAINER 4
#define UI_COMP_HKBUTTONCONTAINER_HKLABELCONTAINER_HKDISPLAYNAME 5
#define UI_COMP_HKBUTTONCONTAINER_HKLABELCONTAINER_HKSTATUS 6
#define _UI_COMP_HKBUTTONCONTAINER_NUM 7
lv_obj_t *ui_hkButtonContainer_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
