// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: JC3248W535CIY

#include "../ui.h"

void ui_comp_hkButtonContainer_create_hook( lv_obj_t * comp)
{
}
