// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: JC3248W535CIY

#ifndef _UI_COMP_OMGLABELCONTAINER_H
#define _UI_COMP_OMGLABELCONTAINER_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT omgLabelContainer
#define UI_COMP_OMGLABELCONTAINER_OMGLABELCONTAINER 0
#define UI_COMP_OMGLABELCONTAINER_OMGTITLE 1
#define UI_COMP_OMGLABELCONTAINER_OMGLINE1 2
#define UI_COMP_OMGLABELCONTAINER_OMGLINE2 3
#define UI_COMP_OMGLABELCONTAINER_OMGLINE3 4
#define UI_COMP_OMGLABELCONTAINER_OMGLINE4 5
#define _UI_COMP_OMGLABELCONTAINER_NUM 6
lv_obj_t *ui_omgLabelContainer_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
