// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: esp32-homebridge

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_Screen1,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Screen1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x6E4B0B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_Screen1, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_Screen1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Screen1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_hkButtonLight5 = ui_hkButtonSwitch_create(ui_Screen1);
lv_obj_set_x( ui_hkButtonLight5, 0 );
lv_obj_set_y( ui_hkButtonLight5, 0 );

ui_hkButtonLight6 = ui_hkButtonSwitch_create(ui_Screen1);
lv_obj_set_x( ui_hkButtonLight6, 0 );
lv_obj_set_y( ui_hkButtonLight6, 0 );

ui_hkButtonLight7 = ui_hkButtonSwitch_create(ui_Screen1);
lv_obj_set_x( ui_hkButtonLight7, 0 );
lv_obj_set_y( ui_hkButtonLight7, 0 );

ui_hkButtonLight8 = ui_hkButtonSwitch_create(ui_Screen1);
lv_obj_set_x( ui_hkButtonLight8, 0 );
lv_obj_set_y( ui_hkButtonLight8, 0 );

ui_hkButtonLight9 = ui_hkButtonSwitch_create(ui_Screen1);
lv_obj_set_x( ui_hkButtonLight9, 0 );
lv_obj_set_y( ui_hkButtonLight9, 0 );

ui_hkButtonLight10 = ui_hkButtonSwitch_create(ui_Screen1);
lv_obj_set_x( ui_hkButtonLight10, 0 );
lv_obj_set_y( ui_hkButtonLight10, 0 );

ui_hkButtonLight11 = ui_hkButtonSwitch_create(ui_Screen1);
lv_obj_set_x( ui_hkButtonLight11, 0 );
lv_obj_set_y( ui_hkButtonLight11, 0 );

ui_hkButtonLight12 = ui_hkButtonSwitch_create(ui_Screen1);
lv_obj_set_x( ui_hkButtonLight12, 0 );
lv_obj_set_y( ui_hkButtonLight12, 0 );

ui_hkButtonLight13 = ui_hkButtonSwitch_create(ui_Screen1);
lv_obj_set_x( ui_hkButtonLight13, 0 );
lv_obj_set_y( ui_hkButtonLight13, 0 );


}
