// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: esp32-homebridge

#ifndef _ESP32_HOMEBRIDGE_UI_H
#define _ESP32_HOMEBRIDGE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_hkButtonLight5;
extern lv_obj_t *ui_hkButtonLight6;
extern lv_obj_t *ui_hkButtonLight7;
extern lv_obj_t *ui_hkButtonLight8;
extern lv_obj_t *ui_hkButtonLight9;
extern lv_obj_t *ui_hkButtonLight10;
extern lv_obj_t *ui_hkButtonLight11;
extern lv_obj_t *ui_hkButtonLight12;
extern lv_obj_t *ui_hkButtonLight13;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_lightoff_png);   // assets/lightOff.png


LV_FONT_DECLARE( ui_font_Montserrat_Bold_14);
LV_FONT_DECLARE( ui_font_Montserrat_Bold_16);
LV_FONT_DECLARE( ui_font_Montserrat_Bold_18);
LV_FONT_DECLARE( ui_font_Open_Sans_12);
LV_FONT_DECLARE( ui_font_Open_Sans_14);
LV_FONT_DECLARE( ui_font_Open_Sans_16);
LV_FONT_DECLARE( ui_font_Open_Sans_18);
LV_FONT_DECLARE( ui_font_Open_Sans_20);
LV_FONT_DECLARE( ui_font_Open_Sans_24);
LV_FONT_DECLARE( ui_font_Open_Sans_26);
LV_FONT_DECLARE( ui_font_Open_Sans_Bold_12);
LV_FONT_DECLARE( ui_font_Open_Sans_Bold_14);
LV_FONT_DECLARE( ui_font_Open_Sans_Bold_16);
LV_FONT_DECLARE( ui_font_Open_Sans_Bold_18);
LV_FONT_DECLARE( ui_font_Open_Sans_Bold_20);
LV_FONT_DECLARE( ui_font_Open_Sans_Bold_24);
LV_FONT_DECLARE( ui_font_Open_Sans_Bold_26);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
