// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: esp32-homebridge

#ifndef _UI_COMP_HKBUTTONSWITCH_H
#define _UI_COMP_HKBUTTONSWITCH_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT hkButtonSwitch
#define UI_COMP_HKBUTTONSWITCH_HKBUTTONSWITCH 0
#define UI_COMP_HKBUTTONSWITCH_BUTTONLABEL 1
#define _UI_COMP_HKBUTTONSWITCH_NUM 2
lv_obj_t *ui_hkButtonSwitch_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
