// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: esp32-homebridge

#include "../ui.h"


// COMPONENT hkButtonSwitch

lv_obj_t *ui_hkButtonSwitch_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_hkButtonSwitch;
cui_hkButtonSwitch = lv_button_create(comp_parent);
lv_obj_set_width( cui_hkButtonSwitch, 150);
lv_obj_set_height( cui_hkButtonSwitch, 150);
lv_obj_set_align( cui_hkButtonSwitch, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_hkButtonSwitch, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( cui_hkButtonSwitch, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(cui_hkButtonSwitch, lv_color_hex(0xA66721), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_hkButtonSwitch, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_src( cui_hkButtonSwitch, &ui_img_lightoff_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_color(cui_hkButtonSwitch, lv_color_hex(0xDECFBF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(cui_hkButtonSwitch, 255, LV_PART_MAIN| LV_STATE_CHECKED);

lv_obj_t *cui_buttonLabel;
cui_buttonLabel = lv_label_create(cui_hkButtonSwitch);
lv_obj_set_width( cui_buttonLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_buttonLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_buttonLabel, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(cui_buttonLabel,"Hallway Light");
lv_obj_set_style_text_font(cui_buttonLabel, &ui_font_Open_Sans_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(cui_buttonLabel, lv_color_hex(0xA66721), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(cui_buttonLabel, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_text_font(cui_buttonLabel, &ui_font_Open_Sans_12, LV_PART_MAIN| LV_STATE_CHECKED);

lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_HKBUTTONSWITCH_NUM);
children[UI_COMP_HKBUTTONSWITCH_HKBUTTONSWITCH] = cui_hkButtonSwitch;
children[UI_COMP_HKBUTTONSWITCH_BUTTONLABEL] = cui_buttonLabel;
lv_obj_add_event_cb(cui_hkButtonSwitch, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_hkButtonSwitch, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_hkButtonSwitch_create_hook(cui_hkButtonSwitch);
return cui_hkButtonSwitch; 
}

