// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: esp32-homebridge

#include "../ui.h"

void ui_comp_hkButtonSwitch_create_hook( lv_obj_t * comp)
{
}
