name: Build binaries, docs and publish to dev folder

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: github.repository_owner == '1technophile'
    outputs:
      short-sha: ${{ steps.short-sha.outputs.sha }}
    steps:
      - uses: actions/checkout@v4
      - uses: benjlevesque/short-sha@v2.1
        id: short-sha
        with:
          length: 6

  handle-firmwares:
    needs: prepare
    name: Build and deploy development firmwares artefacts
    uses: ./.github/workflows/task-build.yml
    with:
      enable-dev-ota: true
      version-tag: ${{ needs.prepare.outputs.short-sha }}
      artifact-retention-days: 1

  handle-documentation:
    needs: [prepare, handle-firmwares]
    name: Build and deploy development documentation
    uses: ./.github/workflows/task-docs.yml
    with:
      mode: "dev"
      version: ${{ needs.prepare.outputs.short-sha }}
      url-prefix: "/dev/"
      destination-dir: "dev"
      run-pagespeed: true
      pagespeed-url: 'https://docs.openmqttgateway.com/dev/'
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      pagespeed-apikey: ${{ secrets.APIKEY }}