name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build firmware
    uses: ./.github/workflows/task-build.yml
    with:
      python-version: '3.13'
      enable-dev-ota: false
      artifact-retention-days: 7
      prepare-for-deploy: false

  documentation:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "14.x"
      - name: Download Common Config
        run: |
          curl -o docs/.vuepress/public/commonConfig.js https://www.theengs.io/commonConfig.js
      - name: Install build dependencies
        run: npm install
      - name: Build documentation
        run: npm run docs:build
