name: Check Code Format

on: [push, pull_request]

jobs:
  lint:
    name: Lint code format
    uses: ./.github/workflows/task-lint.yml
    with:
      source: 'main'
      extensions: 'h,ino'
      clang-format-version: '9'
