name: Create and publish documentation

on:
  workflow_dispatch:
  workflow_call:

jobs:
  documentation:
    name: Build and deploy production documentation
    uses: ./.github/workflows/task-docs.yml
    with:
      mode: "prod"
      version: "auto" # Will detect latest git tag
      url-prefix: "/"
      destination-dir: "."
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
