name: Create and publish documentation

on:
  workflow_dispatch:
  workflow_call:

jobs:
  documentation:
    name: Build and deploy production documentation
    uses: ./.github/workflows/task-docs.yml
    with:
      python-version: '3.11'
      node-version: '14.x'
      version-source: 'release'
      base-path: '/'
      destination-dir: '.'
      generate-webuploader: true
      webuploader-args: '${GITHUB_REPOSITORY}'
      run-pagespeed: false
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}